[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "microtorch"
version = "0.1.0"
description = "Artificial Intelligence library"
authors = [{ name = "Tarang Nair" }]
readme = "README.md"
requires-python = ">=3.7"
dependencies = []
